src/External/UI/Models/ErrorViewModel.cs
namespace UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/External/UI/Controllers/BaseControllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers.BaseControllers;

public abstract class BaseController : Controller
{
}

src/External/UI/Controllers/MaterialController.cs
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers;

public sealed partial class MaterialManagementController
{
    [HttpGet("materials")]
    public IActionResult IndexMaterial()
    {
        return View("Material/Index");
    }
    
    [HttpGet("material")]
    public IActionResult CreateMaterial()
    {
        return View("Material/Create");
    }

    [HttpGet("materials/{id:guid}")]
    public IActionResult EditMaterial(Guid id, CancellationToken cancellationToken)
    {
        return View("Material/Edit");
    }
}

src/External/UI/Controllers/MaterialManagementController.cs
using Web.Controllers.BaseControllers;
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers;

[Route("[controller]")]
public sealed partial class MaterialManagementController : BaseController
{
}

src/External/UI/Controllers/TransactionalPartnerController.cs
using Microsoft.AspNetCore.Mvc;

namespace UI.Controllers;

public sealed partial class MaterialManagementController
{
    [HttpGet("TransactionalPartners")]
    public IActionResult IndexTransactionalPartner(CancellationToken cancellationToken)
    {
        return View("TransactionalPartner/Index");
    }
    
    [HttpGet("TransactionalPartner")]
    public IActionResult CreateTransactionalPartner()
    {
        return View("TransactionalPartner/Create");
    }
    
    [HttpGet("TransactionalPartners/{id:guid}")]
    public IActionResult GetTransactionalPartner(Guid id, CancellationToken cancellationToken)
    {
        return View("TransactionalPartner/Edit");
    }
}

src/External/UI/Views/MaterialManagement/Material/Create.cshtml
<div class="text-left">
    <div class="container">
        <form action="/MaterialManagement/Material" method="POST">
            <div id="BasicMaterialInformation">
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Code</label>
                        <input type="text" name="code" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Name</label>
                        <input type="text" name="name" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Color Code</label>
                        <input type="text" name="colorCode" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Width</label>
                        <input type="text" name="width" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Weight</label>
                        <input type="text" name="weight" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Unit</label>
                        <input type="text" name="unit" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Varian</label>
                        <input type="text" name="varian" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Regional Market</label>
                        @* <select class="form-select" name="regionalMarketId" asp-items="@ViewBag.RegionalMarkets"></select> *@
                        <select class="form-select" name="regionalMarketId"></select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Type</label>
                        @* <select class="form-select" name="materialTypeId" asp-items="@ViewBag.MaterialTypes"></select> *@
                        <select class="form-select" name="materialTypeId"></select>
                    </div>
                </div>
            </div>
            <div class="row" id="MaterialCostManagement">
                <button type="button" onclick="addMaterialCost()" class="btn btn-primary btn-lg btn-block">Add Material Cost</button>
                <table class="table table-bordered" id="materialCost">
                    <thead>
                    <tr>
                        <th>Transactional Partner</th>
                        <th>Surcharge</th>
                        <th>MinQuantity</th>
                        <th>Price</th>
                        <th>Currency Type</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <button id="saveMaterial" type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
        </form>
    </div>
</div>
<script src="~/common/select-option.js"></script>
<script src="~/common/http.js"></script>
<script src="~/materialManagement/material.js"></script>
<script>
function saveMaterial(ele) {
    let formData = getMaterialForm(ele)
    httpPost(formData, `${materialManagementApi}/materials`)
        .done(function(data) {
            location.href = "/MaterialManagement/Materials"
        })
        .fail(function(data) {
            console.log(data)
        })
}

$(document).ready(function () {
    $(document).on("click", "#saveMaterial", function(e) {
        e.preventDefault()
        saveMaterial($(this))
    })
    getMaterialTypes()
    getRegionalMarkets()
    getSuppliers()
})
</script>

src/External/UI/Views/MaterialManagement/Material/Edit.cshtml
<div class="text-left">
    <div class="container">
        <!form>
            <div id="BasicMaterialInformation">
                <input hidden name="id" />
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Code</label>
                        <input type="text" name="code" class="form-control" aria-label="Default" />
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Name</label>
                        <input type="text" name="name" class="form-control" aria-label="Default" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Color Code</label>
                        <input type="text" name="colorCode" class="form-control" aria-label="Default" />
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Width</label>
                        <input type="text" name="width" class="form-control" aria-label="Default" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Weight</label>
                        <input type="text" name="weight" class="form-control" aria-label="Default" />
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Unit</label>
                        <input type="text" name="unit" class="form-control" aria-label="Default" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Varian</label>
                        <input type="text" name="varian" class="form-control" aria-label="Default" />
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Regional Market</label>
                        <select class="form-select" name="regionalMarketId"></select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Type</label>
                        @* <select class="form-select" name="materialTypeId" asp-items="@ViewBag.MaterialTypes"></select> *@
                        <select class="form-select" name="materialTypeId"></select>
                    </div>
                </div>
            </div>

            <div class="row" id="MaterialCostManagement">
                <button type="button" onclick="addMaterialCost()" class="btn btn-primary btn-lg btn-block">Add Material Cost</button>
                <table class="table table-bordered" id="materialCost">
                    <thead>
                    <tr>
                        <th>Transactional Partner</th>
                        <th>Surcharge</th>
                        <th>MinQuantity</th>
                        <th>Price</th>
                        <th>Currency Type</th>
                        <th>Action</th>
                    </tr>

                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <button id="saveMaterial" type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
        </!form>
    </div>
</div>
<script src="~/common/select-option.js"></script>
<script src="~/common/http.js"></script>
<script src="~/materialManagement/material.js"></script>
<script>
function saveMaterial(ele) {
    let formData = getMaterialForm(ele)
    let eleForm = ele.closest("form")
    let basicMaterialInformation = eleForm.find("#BasicMaterialInformation")
    formData.id = basicMaterialInformation.find("input[name='id']").val()
    httpPut(formData, `${materialManagementApi}/materials/${formData.id}`)
        .done(function(data) {
            location.href = "/MaterialManagement/Materials"
        })
        .fail(function(data) {
            alert("some thing went wrong with code: " + data.errors[0].Code + ", and message: " + data.errors[0].Message)
            console.log(data)
        })
}

function getMaterialById() {
    let id = getIdByUrl()
    httpGet(`${materialManagementApi}/materials/${id}`)
        .done(renderMaterial)
        .fail(function(data) {
            alert("some thing went wrong with code: " + data.errors[0].Code + ", and message: " + data.errors[0].Message)
            console.log(data)
        })
}

function renderMaterial(data) {
    let result = data.result
    let basicForm = $('#BasicMaterialInformation')
    
    basicForm.find("input[name='id']").val(result.id)
    basicForm.find("input[name='code']").val(result.code)
    basicForm.find("input[name='name']").val(result.name)
    basicForm.find("input[name='colorCode']").val(result.colorCode)
    basicForm.find("input[name='width']").val(result.width)
    basicForm.find("input[name='weight']").val(result.weight)
    basicForm.find("input[name='unit']").val(result.unit)
    basicForm.find("input[name='varian']").val(result.varian)
    basicForm.find("select[name='regionalMarketId']").val(result.regionalMarket.id).change()
    basicForm.find("select[name='materialTypeId']").val(result.materialType.id).change()
    
    for (let materialCost of result.materialCostManagements) {
        renderMaterialCost(materialCost)
    }
}

$(document).ready(function () {
    $(document).on("click", "#saveMaterial", function(e) {
        e.preventDefault()
        saveMaterial($(this))
    })
    $.when(getSuppliers(), getMaterialTypes(), getRegionalMarkets())
        .then(function() {
            getMaterialById()
        })
})
</script>

src/External/UI/Views/MaterialManagement/Material/Index.cshtml
<div class="text-left" style="margin-bottom: 50px;">
    <h1><b>Materials: </b></h1>
</div>

<div class="text-left" style="margin-bottom: 50px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a type="button" asp-controller="MaterialManagement" asp-action="CreateMaterial" class="btn btn-primary btn-lg btn-block">Create</a>
                <table id="materials" class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Color Code</th>
                        <th>Unit</th>
                        <th>Varian</th>
                        <th>Weight</th>
                        <th>Width</th>
                        <th>Type</th>
                        <th>Regional Market</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/common/http.js"></script>
<script>
    function deleteMaterial(ele) {
        let td = ele.closest("td")
        let materialId = td.find("input[name='id']").val()
        httpDelete(`${materialManagementApi}/materials/${materialId}`)
            .done(function(data) {
                location.href = "/MaterialManagement/Materials"
            })
            .fail(function(data) {
                console.log(data)
            })
    }

    function getMaterials() {
        httpGet(`${materialManagementApi}/materials`)
            .done(renderMaterials)
            .fail(function(data) {
                console.log(data)
            })
    }
    
    function renderMaterials(data) {
        let result = data.result
        let tbodyMaterials = $("#materials").find("tbody")
        
        for(var i = 0; i < result.length; i++) {
            let trBodyData = '<tr>'
            trBodyData += `<td>${result[i].code}</td>
                            <td>${result[i].name}</td>
                            <td>${result[i].colorCode}</td>
                            <td>${result[i].unit}</td>
                            <td>${result[i].varian}</td>
                            <td>${result[i].weight}</td>
                            <td>${result[i].width}</td>
                            <td>${result[i].materialTypeName}</td>
                            <td>${result[i].regionalMarketName}</td>
                            <td>
                                <a type='button' href='Materials/${result[i].id}' class="btn btn-primary btn-lg btn-block">Edit</a>
                                <input hidden name='id' value='${result[i].id}'/>
                                <button type='button' id='deleteMaterial' class='btn btn-primary btn-lg btn-block'>Delete</button>
                            </td>`
            trBodyData += '</tr>'
            
            tbodyMaterials.append(trBodyData)
        }
    }

    $(document).ready(function () {
        $(document).on("click", '#deleteMaterial', function () {
            deleteMaterial($(this))
        })
        getMaterials()
    })
</script>

src/External/UI/Views/MaterialManagement/TransactionalPartner/Create.cshtml
<div class="text-left">
    <div class="container">
        <!form>
            <div id="BasicInformation">
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Name</label>
                        <input type="text" name="name" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Tax No</label>
                        <input type="text" name="taxNo" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Website</label>
                        <input type="text" name="website" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Transactional partner type</label>
                        @* <select class="form-select" name="transactionalPartnerTypeId" asp-items="@ViewBag.TransactionalPartnerTypes"></select> *@
                        <select class="form-select" name="transactionalPartnerTypeId"></select>
                    </div>
                </div>
                <div class="row">
                    <div class="row">
                        <div class="col-md-6">
                            <label class="label label-default">Currency type</label>
                            @* <select class="form-select" name="currencyTypeId" asp-items="@ViewBag.CurrencyTypes"></select> *@
                            <select class="form-select" name="currencyTypeId"></select>
                        </div>
                    </div>
                </div>
                <h3>
                    Contact person information
                </h3>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Contact person name</label>
                        <input type="text" name="contactPersonName" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Tel No</label>
                        <input type="text" name="telNo" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Email</label>
                        <input type="text" name="email" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <h3>
                    Address:
                </h3>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">City</label>
                        <input type="text" name="city" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">District</label>
                        <input type="text" name="district" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Street</label>
                        <input type="text" name="street" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Ward</label>
                        <input type="text" name="ward" class="form-control" aria-label="Default"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label class="label label-default">Zip code</label>
                        <input type="text" name="zipCode" class="form-control" aria-label="Default"/>
                    </div>
                    <div class="col-md-6">
                        <label class="label label-default">Country</label>
                        @* <select class="form-select" name="countryId" asp-items="@ViewBag.Countries"></select> *@
                        <select class="form-select" name="countryId"></select>
                    </div>
                </div>
                <div>
                    <div class="col-md-6">
                        <label class="label label-default">Location type</label>
                        @* <select class="form-select" name="locationTypeId" asp-items="@ViewBag.LocationTypes"></select> *@
                        <select class="form-select" name="locationTypeId"></select>
                    </div>
                </div>
            </div>
            <button id="save" type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
        </!form>
    </div>
</div>
<script src="~/common/select-option.js"></script>
<script src="~/common/http.js"></script>
<script src="~/materialManagement/transactional-partner.js"></script>
<script>
function save(ele) {
    let formData = getTransactionalPartnerForm(ele)
    httpPost(formData, `${materialManagementApi}/transactional-partners`)
        .done(function(data) {
            location.href = "/MaterialManagement/TransactionalPartners"
        })
        .fail(function(data) {
            alert(`${data.errors[0].code}: ${data.errors[0].message}`)
        })
}

$(document).ready(function () {
    $(document).on("click", "#save", function(e) {
        e.preventDefault()
        save($(this))
    })
    getTransactionalPartnerTypes()
    getCountries()
    getCurrencyTypes()
    getLocationTypes()
})
</script>

src/External/UI/Views/MaterialManagement/TransactionalPartner/Index.cshtml
<div class="text-left" style="margin-bottom: 50px;">
    <h1><b>Transactional Partners: </b></h1>
</div>

<div class="text-left" style="margin-bottom: 50px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a type="button" asp-controller="MaterialManagement" asp-action="CreateTransactionalPartner" class="btn btn-primary btn-lg btn-block">Create</a>
                <table id="transactionalPartners" class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Tax No</th>
                        <th>Website</th>
                        <th>Type</th>
                        <th>Currency</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/common/http.js"></script>
<script>
function getTransactionalPartners() {
    httpGet(`${materialManagementApi}/transactional-partners`)
        .done(renderTransactionalPartners)
        .fail(function(data) {
            console.log(data)
        })
}

function renderTransactionalPartners(data) {
    let result = data.result
    let tbodyTransactionalPartners = $("#transactionalPartners").find("tbody")
    
    for(var i = 0; i < result.length; i++) {
        let trBodyData = '<tr>'
        trBodyData += `<td>${result[i].name}</td>
                        <td>${result[i].taxNo}</td>
                        <td>${result[i].website}</td>
                        <td>${result[i].type}</td>
                        <td>${result[i].currency}</td>
                        <td>
                            <a type='button' href='TransactionalPartners/${result[i].id}' class="btn btn-primary btn-lg btn-block">Edit</a>
                            <input hidden name='id' value='${result[i].id}'/>
                            <button type='button' id='deleteTransactionalPartner' class='btn btn-primary btn-lg btn-block'>Delete</button>
                        </td>`
        trBodyData += '</tr>'
        
        tbodyTransactionalPartners.append(trBodyData)
    }
}

function deleteTransactionalPartner(ele) {
    let td = ele.closest("td")
    let transactionalPartnerId = td.find("input[name='id']").val()
    
    httpDelete(`${materialManagementApi}/transactional-partners/${transactionalPartnerId}`)
        .done(function(data) {
            location.href = "/MaterialManagement/TransactionalPartners"
        })
        .fail(function(data) {
            console.log(data)
        })
}
$(document).ready(function () {
    $(document).on("click", '#deleteTransactionalPartner', function () {
        deleteTransactionalPartner($(this))
    })
    getTransactionalPartners()
})
</script>

src/External/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        var apiHost = 'http://localhost:5008'
        var materialManagementApi = `${apiHost}/material-management`
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="MaterialManagement" asp-action="IndexMaterial">Material Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">TTTTT</span>
                </button>
                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
                @*     <ul class="navbar-nav flex-grow-1"> *@
                @*         <li class="nav-item"> *@
                @*             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                @*         </li> *@
                @*         <li class="nav-item"> *@
                @*             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                @*         </li> *@
                @*     </ul> *@
                @* </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @* &copy; 2023 - DDD MrpDanu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>